# Generated by Django 4.2.6 on 2023-10-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fiumers", "0003_alter_customuser_email_alter_customuser_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
